### ISSUE TITLE
Issue with Julia

### ISSUE THREAD

**Issue by JulienPascal** [floswald/cumulus-setup#2]
Hi Florian,

There is a minor issue with "install.sh". Julia is installed, but I can't launch it directly by typing "julia" in the terminal.

I have tried this command:
```bash
echo "alias julia='$HOME/apps/julia-0.5/bin/julia'" >> ~/.bashrc && source ~/.bashrc
```
It works because I can launch Julia by typing "julia". But it also returns me an error message, so it might no be the optimal solution:
![image](https://cloud.githubusercontent.com/assets/15772983/25303432/01ff995c-2753-11e7-99cb-5ee2c830f5e6.png)

To install julia, why don't we add the command instead?
```bash
apt get julia 
```

**Comment by floswald** [comment]
the error seems like there is a type somewhere else in your ~/.bashrc. `install.sh` tries to setup a symlink for `julia` (and for me this worked). do you see this issue after you installed `root` after using my script?
i don't want to use `apt get julia` because it installs `0.4.7`. we are close to `0.6` now...

**Comment by JulienPascal** [comment]
Setting-up the symlink probably failed in the first place (I don't know why).

Logged on my VM as root, I've used your script "install.sh". Then I have used this command: 
```bash
echo "alias julia='$HOME/apps/julia-0.5/bin/julia'" >> ~/.bashrc && source ~/.bashrc
```

What do you mean by "do you see this issue after you installed root after using my script?". Do you mean did I try 
```bash 
 sudo apt get julia
```
after running the script "install.sh"?

**Comment by floswald** [comment]
Yes I updated the script after your install. I think a new install as root
should now work. The problem is that one needs to set up .bashrc for root
from scratch, not for other users. In your version of the install I had
taken that out because I was not sure whether to give you root or not. Now
the script is cleverer I hope because it installs depending on whether you
are root or not.
A new vm to try out would clarify this I think.

**Comment by JulienPascal** [comment]
Hi. So I've started from scratch by creating a new VM. I still get an error message with Julia at line 203:
![image](https://cloud.githubusercontent.com/assets/15772983/25608483/498e244e-2f1b-11e7-9cbe-c7ac94aae3f3.png)

**Comment by JulienPascal** [comment]
But if I cd in the right folder, I can launch Julia by running ./julia:
![image](https://cloud.githubusercontent.com/assets/15772983/25608944/3ea5fb5e-2f1d-11e7-926b-ddf2aa06ec00.png)
So it just a matter of adding a path.

**Comment by floswald** [comment]
argh, i added it to the path but that change only becomes active in a new shell. fixed now.

**Comment by JulienPascal** [comment]
If I execute the following command in the shell 
```bash
alias julia="$HOME/local/bin/julia"
```
then I can launch Julia directly from the terminal. Should I push a new version with this line instead of the version with the similink which does not seem to work for me?
![image](https://cloud.githubusercontent.com/assets/15772983/25609287/dcca518a-2f1e-11e7-8740-bcd063f8cde4.png)

**Comment by floswald** [comment]
no, don't worry. the symlink is not the problem, the problem was that the shell was not reloaded with the new PATH. it should all be fine now (you would have to either add that line  to bashrc anyway or execute each time you log in - completely equivalent to my approach)

**Comment by JulienPascal** [comment]
I started again from scratch and everything went fine during the installation. Nice! I just had to close the terminal and start a new one to be able to launch julia. But I guess it's the normal procedure. We can probably close this issue now.
